In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_excel("../data/raw/road_accident_data.xlsx")

In [3]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 5771
Columns: 22

In [4]:
df.head()

,Accident_ID,Accident_Date,Accident_Time,Report_Timestamp,District,Road_Type,Weather_Condition,Surface_Condition,Light_Condition,Traffic_Density,Vehicle_Type,Driver_Age,Driver_Gender,Alcohol_Involved,Vehicle_Speed_kmph,Helmet_Used,Seatbelt_Used,Cause_Category,Accident_Severity,Casualties_Count,Injury_Type,Emergency_Response_Time_Min
0,KER_ACC_100000,2023-04-25,00:47:00,2023-04-25 02:02:00,Kozhikode,Bridge,Clear,Dry,Night,Medium,Truck,23.0,Male,No,90,Not Applicable,No,Drunk Driving,Minor,1,No Injury,6.0
1,NaN,2024-06-01,19:01:00,2024-06-01 21:29:00,Alappuzha,Urban Road,Clear,NaN,Night,Medium,Motorcycle,32.0,NaN,No,58,Yes,Not Applicable,Mechanical Failure,Minor,1,No Injury,13.0
2,KER_ACC_100002,2025-04-05,05:44:00,2025-04-05 07:37:00,Kannur,Rural Road,Clear,Wet,Night,Low,Car,24.0,Female,Yes,54,Not Applicable,Yes,Mechanical Failure,Serious,1,Minor Injury,13.0
3,KER_ACC_100003,2023-09-28,01:46:00,2023-09-28 03:48:00,Malappuram,Junction,Clear,Dry,Night,Medium,Car,53.0,Female,No,32,Not Applicable,Yes,NaN,Minor,2,Minor Injury,25.0
4,KER_ACC_100004,2023-07-16,22:04:00,2023-07-16 22:20:00,Malappuram,Highway,Fog,Dry,Night,NaN,Car,32.0,Female,No,112,NaN,Yes,Weather Conditions,Serious,2,Major Injury,22.0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5771 entries, 0 to 5770
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Accident_ID                  5515 non-null   str
 1   Accident_Date                5771 non-null   datetime64[us]
 2   Accident_Time                5771 non-null   str
 3   Report_Timestamp             5771 non-null   datetime64[us]
 4   District                     5512 non-null   str
 5   Road_Type                    5510 non-null   str
 6   Weather_Condition            5532 non-null   str
 7   Surface_Condition            5527 non-null   str
 8   Light_Condition              5498 non-null   str
 9   Traffic_Density              5524 non-null   str
 10  Vehicle_Type                 5525 non-null   str
 11  Driver_Age                   5533 non-null   float64
 12  Driver_Gender                5516 non-null   str
 13  Alcohol_Involved             5527 non-null   str
 14  Vehicle_Speed_kmph           5771 non-null   int64
 15  Helmet_Used                  5492 non-null   str
 16  Seatbelt_Used                5547 non-null   str
 17  Cause_Category               5481 non-null   str
 18  Accident_Severity            5496 non-null   str
 19  Casualties_Count             5771 non-null   int64
 20  Injury_Type                  5509 non-null   str
 21  Emergency_Response_Time_Min  5501 non-null   float64
dtypes: datetime64[us](2), float64(2), int64(2), str(16)
memory usage: 992.0 KB

In [6]:
df.describe()

,Accident_Date,Report_Timestamp,Driver_Age,Vehicle_Speed_kmph,Casualties_Count,Emergency_Response_Time_Min
count,5771,5771,5533.000000,5771.000000,5771.000000,5501.000000
mean,2024-03-14 13:11:44.280020,2024-03-15 02:42:35.785825,44.524309,70.663317,1.707850,19.922923
min,2023-01-01 00:00:00,2023-01-01 07:01:00,18.000000,20.000000,0.000000,5.000000
25%,2023-07-31 00:00:00,2023-07-31 20:40:00,31.000000,55.000000,1.000000,12.000000
50%,2024-03-16 00:00:00,2024-03-17 02:04:00,44.000000,70.000000,2.000000,19.000000
75%,2024-10-22 00:00:00,2024-10-22 19:47:30,58.000000,87.000000,2.000000,25.000000
max,2025-05-30 00:00:00,2025-05-31 02:07:00,420.000000,120.000000,7.000000,222.000000
std,NaN,NaN,19.330441,22.042187,1.280397,10.507377

In [7]:
df.nunique().sort_values()

Driver_Gender                     2
Alcohol_Involved                  2
Surface_Condition                 3
Light_Condition                   3
Traffic_Density                   3
Helmet_Used                       3
Accident_Severity                 3
Seatbelt_Used                     3
Weather_Condition                 4
Injury_Type                       4
Vehicle_Type                      5
Road_Type                         5
Cause_Category                    5
Casualties_Count                  8
District                         14
Emergency_Response_Time_Min      62
Driver_Age                       67
Vehicle_Speed_kmph              101
Accident_Date                   879
Accident_Time                  1414
Accident_ID                    5469
Report_Timestamp               5711
dtype: int64

In [8]:
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

categorical_cols = df.select_dtypes(include=['object', 'string']).columns

datetime_cols = df.select_dtypes(include=['datetime']).columns

print("Numerical:")
print(numerical_cols)

print("\nCategorical:")
print(categorical_cols)

print("\ndatetime:")
print(datetime_cols)

Numerical:
Index(['Driver_Age', 'Vehicle_Speed_kmph', 'Casualties_Count',
       'Emergency_Response_Time_Min'],
      dtype='str')

Categorical:
Index(['Accident_ID', 'Accident_Time', 'District', 'Road_Type',
       'Weather_Condition', 'Surface_Condition', 'Light_Condition',
       'Traffic_Density', 'Vehicle_Type', 'Driver_Gender', 'Alcohol_Involved',
       'Helmet_Used', 'Seatbelt_Used', 'Cause_Category', 'Accident_Severity',
       'Injury_Type'],
      dtype='str')

datetime:
Index(['Accident_Date', 'Report_Timestamp'], dtype='str')

In [9]:
missing_values = df.isnull().sum()
missing_percentage = (missing_values / len(df)) * 100

missing_df = pd.DataFrame({
    'Missing Values': missing_values,
    'Percentage': missing_percentage
})

missing_df.sort_values(by='Percentage', ascending=False)

                             Missing Values  Percentage
Cause_Category                          290    5.025126
Helmet_Used                             279    4.834517
Accident_Severity                       275    4.765205
Light_Condition                         273    4.730549
Emergency_Response_Time_Min             270    4.678565
Injury_Type                             262    4.539941
Road_Type                               261    4.522613
District                                259    4.487957
Accident_ID                             256    4.435973
Driver_Gender                           255    4.418645
Traffic_Density                         247    4.280021
Vehicle_Type                            246    4.262693
Surface_Condition                       244    4.228037
Alcohol_Involved                        244    4.228037
Weather_Condition                       239    4.141397
Driver_Age                              238    4.124069
Seatbelt_Used                           224    3.881476
Accident_Date                             0    0.000000
Accident_Time                             0    0.000000
Report_Timestamp                          0    0.000000
Vehicle_Speed_kmph                        0    0.000000
Casualties_Count                          0    0.000000

In [10]:
total_cells = df.shape[0] * df.shape[1]
missing_cells = df.isnull().sum().sum()

missing_percentage = (missing_cells / total_cells) * 100

print(f"Total Missing Values: {missing_cells}")
print(f"Missing Percentage: {missing_percentage:.2f}%")

Total Missing Values: 4362
Missing Percentage: 3.44%

In [11]:
duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

Duplicate Rows: 47

Data Quality Issue Log

Issue           Observation

Missing Values	~4%
Duplicate Rows	50
Outliers	    Expected in numerical columns
Date Columns	Need datatype conversion
Categorical     Standardization	To be checked

Business Questions

1. Which district has the most accidents?
2. Does weather influence accident severity?
3. Are night-time accidents more severe?
4. Does overspeeding increase casualties?
5. Which vehicle types are most accident-prone?
6. Do helmets and seatbelts reduce severity?
7. Do drunk-driving accidents cause more fatalities?